server:
  port: 8080

spring:
  datasource:
    username: root
    password: Kdd1973#2010
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

# example values

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.ru
    #    - url: https://volochek.life
    #      name: Volochek.ru
    - url: https://www.lenta.ru
      name: Лента.ру
    #    - url: https://www.skillbox.ru
    #      name: skillbox.ру
    #    - url: https://dombulgakova.ru
    #      name: Dom_Bulgakova.ru
    #    - url: https://dimonvideo.ru
    #      name: DimonVideo.ru
    #    - url: http://radiomv.ru
    #      name: Radiomv.ru
    #    - url: https://ipfran.ru
    #      name: Ipfran.ru
    #    - url: https://nikoartgallery.com
    #      name: Nikoartgallery.com
    #    - url: https://et-cetera.ru
    #      name: Et-cetera.ru
    #    - url: https://www.lutherancathedral.ru
    #      name: Lutherancathedral.ru
    - url: https://www.svetlovka.ru
      name: Svetlovka.ru